Update Flask version.
Currently the application will fail to build with the error:
ImportError: cannot import name 'escape' from 'jinja2'

This change simply updates the version of flask so it does not attempt
to import excape from jinja2.

Signed-off-by: Casey Flynn <caseyflynn@google.com>