Update Flask Version
Currently the sample code errors out with the error:
ImportError: cannot import name 'escape' from 'jinja2'

This change simply updates the version of Flask used so
it no longer attempts to import excape from jinja2.

Signed-off-by: Casey Flynn <caseyflynn@google.com>